insanum/gcalcli

gcalcli

This includes support for all-day events.
I added the '--allday' flag and if you use it, then only the date portion of --when will be used, and --duration is in days rather than minutes.
You can add events, or edit existing events (and if you edit, you can turn a partial-day event into an all-day event or vice versa).

Added support for all-day events

---

gcalcli

When I execute these commands, I will see ***UnicodeDecodeError*** .
```
$ gcalcli calw
$ gcalcli calm
$ gcalcli agenda
```
It is becaues there are utf-8 string type (like Japanese) in schedules.
So I fixed this problem.

Countermeasure for UnicodeDecodeError

---

setup.py

The package "dateutils" referred to in setup.py is this one https://pypi.python.org/pypi/dateutils. I think the one that was actually meant was "python-dateutil" which is here: https://pypi.python.org/pypi/python-dateutil/
The reason setup.py currently works is because the "dateutils" package pulls in "python-dateutil" as a dependency.

Use correct package name for dateutil

---

gcalcli

By default, no guests will be added, nor will it be prompted. However, you can specify as many --who options as you want when adding an event.

Add support to add guests to events

---

gcalcli

gcalcli crashed when trying to print an event in a Google+ calendar:
$ gcalcli --nocolor --nolineart --details=all agenda 2016-01-{30,31}
Sa Jan 30  08:30  FOSDEM 2016
Calendar: tschwinge@googlemail.com
Link: https://plus.google.com/events/ck7ros5lr0usntht458tt6fsqgc
Location: ULB, Avenue Franklin Roosevelt, Brussels, Belgium
Attendees:
DEBUG [u'displayName', u'id']
Traceback (most recent call last):
File "./gcalcli", line 2588, in <module>
BowChickaWowWow()
File "./gcalcli", line 2436, in BowChickaWowWow
gcal.AgendaQuery(startText=args[1])
File "./gcalcli", line 1692, in AgendaQuery
self._IterateEvents(start, eventList, yearDate=False)
File "./gcalcli", line 1537, in _IterateEvents
self._PrintEvent(event, prefix)
File "./gcalcli", line 1274, in _PrintEvent …

Don't crash if organizer or attendees' email addresses are not provided

---

gcalcli

This adds the `--nodeclined` attribute, which allows for ignoring events which are declined in the calendar.

Allow ignoring declined events

---

gcalcli

Events where nobody is invited will not have any attendees, and cannot be declined.

Don't error out for events with no attendees

---

gcalcli

This is #263 on top of 4.0's `argparse_over_gflags` branch.
It occurs to me that you might want to do this more generically, e.g. something like `--hide=sat --hide=sun`, although as written it should cover the most common use case for a feature like that.

Add a --noweekend option to hide Saturday and Sunday

---

gcalcli

This commit is based on the branch `argparse_over_gflags`, since `v4.0.0a3` cannot be based and `master` has a huge difference from it
**Before commit**
**After commit**

Fix text-wrap when widechar appeared at cut index

---

gcalcli

This patch adds support for display allDay events which takes more than
one day not only on first day of event but on all days.
It is displayed in calm and calw view.
Fixes #12

Add support for display of multidays allday events

---

docs/README.md
docs/man1/gcalcli.1
gcalcli/gcalcli.py

Pass a standard icon name to ```notify-send``` so the notification popup looks nicer.

Add a standard icon for notification

---

gcalcli/argparsers.py
gcalcli/gcalcli.py
gcalcli/utils.py
tests/test_gcalcli.py

Please find this PR in response to #393.
User is able to override the colour of a new event using the `--color` flag. Valid colour values match that in Google Calendar UI ("lavender", "grape", etc).
When viewing events using `agenda`, `calm` or `calw` commands, the overridden colours can be viewed using the `--override-color` flag.  Colours can be edited in using the `edit` command.
I have decided not to implement any locale-based code (for `--colo[u]r`) at this stage, but I'm interested in coming back to that.
This code (colour output in terminal/browser) is very difficult to test, so I have not gone down that route at this stage, although I am interested in the general desire to write better unit tests for this software and may sumit issues/PRs for this in future.
`edit --help` shows …

Ability to override and edit event colour

---

gcalcli/argparsers.py
gcalcli/exceptions.py
gcalcli/gcalcli.py
gcalcli/utils.py
gcalcli/validators.py
tests/conftest.py
tests/test_gcalcli.py
tests/test_input_validation.py

Please find this PR for #399 as promised.
This is quite a hefty PR, however I have tried hard not to disrupt the flow of `main()` at all.
I have created `gcalcli.validators` module where the main work is done. Instead of calling `input()` in `main()` to capture options, a new function `get_input()` does the job. It wraps a `while()` loop prompting the user to enter something that passes a specific match condition, which it gets from a callable passed into `get_input()`. There are a number of validator callables - basically very simple functions that return their argument if they pass a certain test or raise a `ValidationError` (from `gcalcli.exceptions`) if they don't, e.g.
```python
def str_to_int_validator(input_str):
"""
A filter allowing any string which can be
converted to an int. …
```

Better user interaction during prompts when adding an event

---

gcalcli/gcalcli.py

This was left over after earlier merge and breaks the application if for anyone currently using master if not passing in `configFolder` option.

Fixed variable left in code after PR #411

---

gcalcli/argparsers.py
gcalcli/decorators.py
gcalcli/gcalcli.py
tests/test_argparsers.py

WIP PR reference #382.
Uses a decorator to allow new "dashed" semantics (e.g. "--color-owner").
Does not decorate work with the core parser as yet, but does so with color/reminder parsers.
Very grateful for comments and feedback!

382 parser warnings

---

docs/README.md
setup.py

Since v4.0.0 parsedatetime has been a requirement. (https://github.com/insanum/gcalcli/commit/166a58a81068cef858caece10e41db591f98ac53) parsedatetime was originally an "extra", a recommended optional package. The commit adding it as a hard dependency didn't remove it from the list of extras.
Before this change both docs/README.md and setup.py list parsedatetime twice. After this change parsedatetime is not described as optional.

parsedatetime is not an optional requirement

---

ChangeLog
gcalcli/argparsers.py
gcalcli/gcal.py
setup.py
tests/test_argparsers.py

Google has removed the urlshortening service.  After some discussion,
it was decided to remove the shortening facilities instead of trying to
integrate with a separate provider.  This makes our code simpler and
folks who need url shortening can hopefully layer on what they need.

Remove URL Shortening [fixes #440]

---

docs/README.md

See #440
Noticed that the feature had been removed, but was still listed in the readme file.

Remove url shortening from feature list in readme

---

gcalcli/gcal.py

If there is no `--calendar` specified, nor `defaultCalendar` set, ask the user to select one of the available calendars.

Add prompt for calendar for 'add' command

---

gcalcli/argparsers.py
tests/test_argparsers.py

If there is no `-w` nor `--width` specified calculate maximum console width that is available, but no less then 10 columns for `cal_width`.

Automatically use available console width

---

gcalcli/gcal.py

Show only writable calendars in prompt for `add`

---

gcalcli/gcal.py
tests/test_gcalcli.py

Fixes an IndexError thrown in `_DeclinedEvent` if no attendee with a matching email can be found when checking if an event has been declined (through `--nodeclined`).

Don't throw IndexError if attendee cannot be found in _DeclinedEvent

---

docs/README.md

WARNING: --client_id has been deprecated and will be removed in a future release.
Please use "--client-id", instead.
WARNING: --client_secret has been deprecated and will be removed in a future release.
Please use "--client-secret", instead.

Correct the gcalclirc keys

---

docs/README.md
docs/man1/gcalcli.1
gcalcli/argparsers.py
gcalcli/cli.py
gcalcli/conflicts.py
gcalcli/gcal.py
tests/test_argparsers.py
tests/test_conflicts.py
tests/test_gcalcli.py

This is useful for finding scheduling conflicts with your current events.
Future potential features:
- add flag for a "buffer time" (e.g. 30 minutes) to account for travel time
- add flag to import to check for conflicts before importing

Add conflicts command

---

gcalcli/cli.py
gcalcli/gcal.py
gcalcli/utils.py
gcalcli/validators.py
tests/test_input_validation.py
tests/test_utils.py

For example
- 3.5h
- 3m
- 2 (defaults to minutes)
- 2h4m2s
Fixes #514

Allow duration to be specified in multiple formats

---

gcalcli/argparsers.py
gcalcli/cli.py
gcalcli/details.py
gcalcli/exceptions.py
gcalcli/gcal.py
gcalcli/utils.py
tox.ini

Add the `agendaupdate` subcommand, the minimum viable product for #550.
Refactor `gcalcli.gcal.GoogleCalendarInterface._tsv()`, replacing the long list of if statements with a modular design using a series of `gcalcli.details.Handler` classes.
My plan is to keep making additions to the michaelmhoffman/issue-550 branch, pushing from my local machine when I have changes that implement each of the checklist items in #550. I test locally with Python 3.5-Python 3.8. Please feel free to review and apply now or when I'm done with the whole set.

Add `agendaupdate` subcommand

---

gcalcli/gcal.py
mypy.ini

Fixes #612.
Make MyPy ignore missing imports.
- build(mypy): add `mypy.ini` with `ignore_missing_imports = True`
- style: add extra line to satisfy flake8 `E02`

build(mypy): add `mypy.ini` with `ignore_missing_imports = True`

---

docs/README.md

Add links to the new GoogleDevConsole.
Inform users about the OAuth2 API (verification) limit.

'docs: `README.md`: straightforward instructions for Google dev console (#573)

---

docs/README.md

Void Linux now has gcalcli in their [repositories](https://voidlinux.org/packages/?arch=x86_64&q=gcalcli). Maybe include this information in the README?

docs: `README.md`: add Void Linux

---

setup.py
tox.ini

These are the released versions of Python that are currently
supported by the Python core developers.
https://devguide.python.org/versions/
Might be a few flake8 errors on this version. This is to be corrected
by a subsequent pull request that will fix import orders.

build: change supported Python versions to 3.8, 3.9, 3.10, 3.11

---

ChangeLog
docs/README.md
gcalcli/argparsers.py
tests/data/cal_service_discovery.json
tests/test_conflicts.py

Found via `codespell -S htmlcov`

docs: fix typos

---

gcalcli/gcal.py

Report the actual start_time value that couldn't be parsed so it's clearer when gcalcli is doing something silly like interpreting --calendar=Foo as a positional arg (see #697).

Improve error message for "failed to parse start time"

---

ChangeLog
gcalcli/argparsers.py
tests/test_gcalcli.py

Configures file arguments with errors='replace' so that if they encounter characters they can't encode/decode they'll just replace them with a replacement marker such as '?' instead of raising an exception.
Fixes #387 (probably)

Fix import and agendaupdate to handle encoding errors more gracefully

---

ChangeLog
gcalcli/argparsers.py
gcalcli/cli.py
gcalcli/gcal.py
gcalcli/utils.py

Instead of specifying an event duration during creation, it can be useful to give an event end time. This commit adds a --end flag that can be used as an alternative to the --duration flag.
The --end flag takes a date string similar to the --when flag.
It's an error to supply both --end and --duration flags. Given neither flag, duration will be asked for in interactive mode.
Updated replacement for PR #307.

Add --end flag for add command

---

gcalcli/gcal.py

When a large list of events was obtained, only the first query was correct. Subsequent queries used default parameters, so the resulting list had the earliest events of the calendar, etc. (The Google API may have changed since the affected code was written.)
An illustration:
```sh
$ pip install --upgrade git+https://github.com/insanum/gcalcli
$ gcalcli agenda --tsv 2021-01-01 2021-12-31 | head -n3 | cut -f1-4
start_date	start_time	end_date	end_time
2012-05-17	21:00	2012-05-17	22:00  # the very first event in my default calendar
2012-07-17	11:00	2012-07-17	12:00
$ pip install --upgrade git+https://github.com/kbulygin/gcalcli
$ gcalcli agenda --tsv 2021-01-01 2021-12-31 | head -n3 | cut -f1-4
start_date	start_time	end_date	end_time
2020-12-31	20:00	2021-01-01	03:00  # correct
2021-01-01 …
```

fix event list: configure all page queries, not just the first one

---

ChangeLog
gcalcli/gcal.py

Ensures that requests using pageToken preserve the same parameters as the initial request to avoid returning non-matching items after the first page.
Fixes issue mentioned in PR #664.

Fix event list lookups returning incorrect events due to pagination

---

ChangeLog
gcalcli/argparsers.py
gcalcli/gcal.py
gcalcli/ics.py
tests/test_gcalcli.py

For events that contain a UID field, use Google Calendar's event [import](https://developers.google.com/calendar/v3/reference/events/import) feature instead of [insert](https://developers.google.com/calendar/v3/reference/events/insert) to avoid creating duplicates.
Note that events with UID populated may still get processed as new/updated events if the SEQUENCE number is also incremented (https://www.kanzaki.com/docs/ical/sequence.html).
Fixes #492 & #583.

Avoid creating duplicate events by respecting the UID field

---

.github/workflows/tests.yml
.gitmodules
CONTRIBUTING.md
pyproject.toml
tests/README.md
tests/cli/test.bats
tox.ini

So far just a few tests to run gcalcli with no commands and with `--help`, but it's a foundation we can build on incrementally.
Fixes #419.

Add basic cli tests using Bats

---

gcalcli/__init__.py
gcalcli/argparsers.py
gcalcli/auth.py
gcalcli/deprecations.py
gcalcli/gcal.py

Improve auth setup experience with more self-contained explanations/links

---

.gitignore
gcalcli/__init__.py
pyproject.toml

Magically loads versions from git tags, with suffixes on dev builds that don't come from an exact tag commit.

tooling: source gcalcli version from setuptools-scm instead of py string

---

.github/workflows/tests.yml
gcalcli/_types.py
gcalcli/conflicts.py
gcalcli/deprecations.py
gcalcli/details.py
gcalcli/gcal.py
gcalcli/ics.py
pyproject.toml
tox.ini

Bump `project.requires-python`, remove py3.8 and py3.9 from test matrix, and clean up compatibility cruft for older python versions.

Bump requires-python to ">= 3.10"

---

CONTRIBUTING.md
pyproject.toml
tox.ini

While doing [4.4.0 release build](https://github.com/Homebrew/homebrew-core/pull/182881), seeing bunch of dev deps pulled in, thus updating the pyproject.toml.

chore: move dev deps into `project.optional-dependencies`

---

gcalcli/gcal.py

At the moment, only a backtrace is printed and it doesn't make what's going on obvious.
This is especially important now as the migration from oauth2client to google-auth comes with a format change for this file and anyone who had been using gcalcli successfully before is likely to encounter this error.
I've tested this change the following way in a container:
```
Couldn't parse /root/.gcalcli_oauth.
The file may be corrupt or be incompatible with this version of gcalcli. It probably has to be removed and provisioning done again.
[backtrace]
```
This doesn't cover the file being empty but a) this is quite unlikely to happen, b) the cause would be completely different; moreover the exception is quite clear: `EOFError: Ran out of input`
Helps with #691.

feat: print an error message when ~/.gcalcli_oauth deserialization fails

---

gcalcli/auth.py

Wrap weird SSL RecursionError in a nicer error hinting at workaround

---

ChangeLog
gcalcli/argparsers.py
gcalcli/cli.py
gcalcli/gcal.py
pyproject.toml
tests/conftest.py
tests/test_auth.py

Uses platformdirs to determine appropriate data file paths for each platform (e.g. under ~/.local/share/ or ~/Library/Application Support/).
Fixes #640.

Migrate data files like ~/.gcalcli_oauth into standard data file paths

---

ChangeLog
gcalcli/argparsers.py

Support $GCALCLI_CONFIG env var, deprecate --config-folder, improve help

---

.gitignore
MANIFEST.in
data/config-schema.json
gcalcli/argparsers.py
gcalcli/cli.py
gcalcli/env.py
gcalcli/gcal.py
pyproject.toml

Initially this just supports a single config key, calendars.default-calendar.
Fixes #416.

Add support for parsing config.toml from config dir

---

data/config-schema.json
gcalcli/argparsers.py
gcalcli/cli.py

Renames config value, updates --help to explain the config, and also tweaks the other config paths reported in --help to be a bit shorter and more readable.
Follow-up from #744, helps with #416.

New config.toml: rename default-calendar->default-calendars, add note config.toml file into --help

---

data/config-schema.json
docs/README.md
gcalcli/argparsers.py
gcalcli/cli.py
gcalcli/gcal.py
tests/cli/__snapshot__/test-02-test_prints_correct_help.snap
tests/conftest.py

Implement a config option for ignoring a list of calendars by name from the set of selected calendars to display/use in different commands.
Fixes #597.

Config: add a calendars.ignore-calendars option

---

ChangeLog
gcalcli/argparsers.py
gcalcli/cli.py
tests/cli/__snapshot__/test-02-test_prints_correct_help.snap
tests/test_argparsers.py

Updates handling of --calendar to stop relying on brittle handle_unparsed hack and use more self-aware parsing per command.
Also updates --noincluderc to work more comprehensively (w/ or w/o --config-folder), so that it's easier to ensure other calendars listed in configs don't leak into a given gcalcli run.
Fixes #697 and #757.

Improve handling of --calendar and --noincluderc args

---

gcalcli/cli.py
tests/test_gcalcli.py

Fix parsing for calendar names containing '#'

---

ChangeLog
gcalcli/cli.py
gcalcli/utils.py
gcalcli/validators.py
pyproject.toml
tests/cli/__snapshot__/test-04-test_can_run_add.snap
tests/test_input_validation.py

Fixes #542.
Fixes #143.
Note: This adds a new dependency on [babel](https://pypi.org/project/babel/), which isn't tiny. _COULD_ convert that to optional-dependencies if absolutely needed, but I'd prefer to keep it an unconditional dep since i18n/l10n are pretty important aspects of a tool like gcalcli.

Determine date format to use based on system locale's in "When" inputs

---

ChangeLog
gcalcli/ics.py

Fixes #486.
Credit: Changes taken from #282 and rebased onto main, with trivial cleanups and a tweak to the dtstart-only case (30m duration + info message instead of 0m duration).

CreateEventFromVOBJ: if there is no dtend, use the duration if available

---

gcalcli/gcal.py

Helps #730 (by making workaround more discoverable).

Add --use-legacy-import hint message in `import` partial-failure output

---

docs/man1/gcalcli.1

Also remove suggestion to "Upgrade to Python3" since it's very very hard for someone to successfully run EOL Python2 or older versions these days. =)

Update man page with latest options

---

gcalcli/__init__.py
gcalcli/argparsers.py
gcalcli/cli.py

I'm **not planning to merge this** without explicit :+1: from authors, but wanted to make _some_ kind of tweak to the `--version` output to better reflect the community maintenance of recent gcalcli versions. Not sure the exact convention for including author names in `--version` output, but it seemed simplest to just omit author info here instead of trying to reflect `authors: X, Y, Z; maintainers: A, B`.
Note authors are still listed in the man page and I'm not worried about changing that (since we already list the bug tracker for reaching maintainers).

Simplify --version to omit author names

---

ChangeLog
gcalcli/cli.py
gcalcli/utils.py
gcalcli/validators.py

ISO-8601-like date formats shouldn't depend on system locale by default, only localized formats like DD-MM-YYYY or MM-DD-YYYY.
Fixes #792.

Adjust "when" value parsing to handle YYYY-MM-DD consistently

---

ChangeLog
gcalcli/cli.py

Fixes #735.
Modifies previous #726.
@ajkessel

Fix bizarre SSL recursion errors by moving truststore init earlier

---

ChangeLog
gcalcli/cli.py
gcalcli/gcal.py

Fix redundant "Ignore and refresh" prompt from `init`

---

ChangeLog
gcalcli/argparsers.py
gcalcli/cli.py
gcalcli/env.py
gcalcli/gcal.py
gcalcli/utils.py
tests/cli/__snapshot__/test-02-test_prints_correct_help.snap

Support oauth (and cache) files in $GCALCLI_CONFIG dir

---

gcalcli/gcal.py

Inconsistent variable name resulted in pagenation not working at all. L344 uses the variable name `page_token` not `pageToken`

Fixed pagenation

---

gcalcli/argparsers.py
gcalcli/gcal.py
tests/test_argparsers.py
tests/test_gcalcli.py

Fix the width for the description details, both default and as cmdline option, and make sure we don't break the width of the `calw` and `calm` output.
The (pretty much undocumented) option` --width`/`-w` option was used for setting the width of a day table cell in `calw` and `calm` but seemed to also be intended for setting the overall width of the `description` in `agenda`. The latter part was broken and the details `description` width would always default to 80.
We change the behaviour to set the overall width of the table, defaulting to the terminal width, both for `calw` and `calm` and for `description` details. The width of the day cell is calculated from the overall width.

Fix width argument, set overall width

---

gcalcli/gcal.py

This pull request fixes calculating the width when calw/calm is used with the option `--noweekend`
The `day_width` was calculated assuming 7 days a week. This is of course not correct when `--noweekend` is set. The variable `days` was already calculated in `_GraphEvents`, so move it to instance level and set it in `__init__()` and use it to calculate the correct width.
Note that this issue already existed before the width argument was fixed in #825 : https://github.com/insanum/gcalcli/commit/e0e126e7660286226370ddf6c21236928e1a4e0d#diff-bdae32b0ae73657fd85ec3f881c2bcce2a0bfa93febd682ccc2febbb711e9cb6L150
Using a terminal width of 106 for which can completely fill both for 5 days (`5*20+6 = 106`) and 7 days (`7*14+8 = 106`).
```
[root@5b33b3d3ea4a gcalcli]# gcalcli calm …
```

Fix width for --noweekend option of calw and calm

---

gcalcli/actions.py
gcalcli/details.py

Implements #791. Resubmission of accidentally closed pull request #817.
To eliminate the possibility of conflicts between `length` and `end_date`/`end_time`, this raises `NotImplementedError` if input is supplied with both of the fields.
In the future, the following would be better conflict resolution approaches:
1. allow both end fields and length field long as they are consistent in each row
2. conflict resolution by command-line option (e.g. prefer end fields or prefer length field)
3. conflict resolution interactively

 agenda and agendaupdate: add --details length redux

---

gcalcli/argparsers.py
gcalcli/details.py
gcalcli/gcal.py

This PR extends the `--tsv` output mechanism to provide an alternative `--json` output format.
Implements #466 
For consistency, anywhere where there's a json dict, the key names use the TSV column name.
As part of this,
* plumbed `attendees` detail handlers.  (`attendees` for TSV is semi-colon delimited email addresses)
* fixed some subclasses?
* `email` is more tolerant of creator/organizer

Add --json output option
