- gcalcli
Replace by %Y-%m-%d which is supported on all platforms, I think.
> Remove nonstandard %F time format

- docs/README.md
This should help people with issue #197
Thanks!
Scott
> README update for using your own Calendar API credentials.

- gcalcli
This might not be the ideal way to fix this, but it works for me
> add --nostarted support to --tsv

- gcalcli
To be able to display attachment infomation when calling with "--details all" or "--details attachments"
> Add attachments display in details

- gcalcli
Fixes https://github.com/insanum/gcalcli/issues/192
I tried making it consistent with calw coloring, so please tell if you notice any potential issues!
> Support for color_now_marker in agenda

- ChangeLog
- gcalcli
- setup.py
This fixed the problems with the import subcommand failing reported in #325.
> Fix import error

- .coveragerc
- .gitignore
- .travis.yml
- gcalcli/gcalcli.py
- setup.cfg
- setup.py
- tests/test_gcalcli.py
- tox.ini
In order to get testing working nicely with pytest and tox, I had to go
ahead and add a package directory going and make some changes to
setup.py
Setup flake8 to run with tox and therefore linted everything.
I'd like to drop support for 2.6, I've removed it from the setup.py file.
> Testing framework setup [fixes #343]

- gcalcli/gcalcli.py
- setup.py
- tests/data/cal_list.json
- tests/data/cal_service_discovery.json
- tests/test_gcalcli.py
Simplified the option processing of the GoogleCalendarInterface class.
> Added some httpmocks moving towards real tests

- docs/README.md
Added apt-get and nix installation instructions
> Added install methods

- gcalcli/gcalcli.py
> fix for KeyError exception raised when running gcalcli remind

- gcalcli/validators.py
> quick fix to re-enable edit of colour after refactor

- gcalcli/argparsers.py
This only changes the default value.
I have also added the --no-military option to
force showing 12 hour time.
> Determine if time should be 24 hours from locale

- docs/README.md
- docs/man1/gcalcli.1
- gcalcli/argparsers.py
- gcalcli/cli.py
- gcalcli/gcal.py
- tests/test_argparsers.py
- tests/test_gcalcli.py
Use case: keeping a paper calendar in sync with an electronic Google calendar.
> Add 'updates' command.

- gcalcli/gcal.py
Item missed in commit 12f7186789eb9f82b7326b420e52acbc5bfde7f3.
This fixes #489.
> Fix "cleanup of javaesque casing"

- .travis.yml
- docs/README.md
- gcalcli/argparsers.py
- gcalcli/cli.py
- gcalcli/deprecations.py
- gcalcli/gcal.py
- gcalcli/printer.py
- gcalcli/utils.py
- gcalcli/validators.py
- setup.py
- tests/test_gcalcli.py
- tests/test_input_validation.py
- tests/test_printer.py
- tests/test_utils.py
- tox.ini
Removes:
* from __future__ imports
* six
* special _u function for handling python2 unicode
Updates:
* setup.py and README to indicate P3K required
* adds python3.7 and 3.8 tox test envs
* adds python3.7 to travis
> Remove Python2 support

- gcalcli/argparsers.py
- gcalcli/gcal.py
> Add `agenda --details conference`

- setup.py
> setup.py: add python_requires

- docs/README.md
Don't mind just learning about github without breaking anything
> A little tiny letter added

- gcalcli/actions.py
- gcalcli/argparsers.py
- gcalcli/cli.py
- gcalcli/deprecations.py
- gcalcli/details.py
- gcalcli/gcal.py
- gcalcli/utils.py
- gcalcli/validators.py
- setup.cfg
- setup.py
- tests/conftest.py
- tests/test_argparsers.py
- tests/test_cli.py
- tests/test_conflicts.py
- tests/test_gcalcli.py
- tests/test_input_validation.py
- tests/test_printer.py
- tests/test_utils.py
- build: set up flake8 and isort Google-like import order
- style: fix import order
- style: fix minor flake8 complaints
Fixes #661.
> style: fix disorganized imports

- gcalcli/argparsers.py
The original description did not fit the purpose of the argument
> Fix help line for "add --who"

- gcalcli/argparsers.py
- gcalcli/printer.py
> document color printing in help / argument errors.

- CONTRIBUTING.md
Capturing a few up-to-date details after discussion in #688.
Fixes #534.
> Add a CONTRIBUTING.md with notes about community/reviews/guidelines/tests

- gcalcli/gcal.py
- tests/test_gcalcli.py
> Fix --nodeclined choking on invites sent to an alias email

- gcalcli/gcal.py
- tests/test_gcalcli.py
> Update quick to prompt for cal when ambiguous, like add already does

- gcalcli/__init__.py
> Bump version to 4.4.0

- gcalcli/cli.py
- pyproject.toml
New PR based on latest upstream code to enable truststore support
Fixes #726.
> add truststore support

- ChangeLog
- docs/man1/gcalcli.1
- gcalcli/argparsers.py
- gcalcli/auth.py
- gcalcli/gcal.py
> auth flow: reintroduce --noauth_local_server arg to provide port forwarding instrs

- ChangeLog
- data/config-schema.json
- docs/README.md
- gcalcli/argparsers.py
- gcalcli/cli.py
- gcalcli/config.py
- gcalcli/gcal.py
- pyproject.toml
- tests/cli/__snapshot__/test-02-test_prints_correct_help.snap
> config: Add output.week-start="sunday"|"monday" setting

- ChangeLog
- gcalcli/argparsers.py
- gcalcli/cli.py
- gcalcli/env.py
- gcalcli/gcal.py
- tests/cli/__snapshot__/test-02-test_prints_correct_help.snap
Useful in the case of caching bugs like #622 (though note it's a workaround, not a fix).
> Add a `util reset-cache` command

- gcalcli/cli.py
- tests/cli/__snapshot__/test-04-test_can_run_add.snap
> add: make --default-reminders skip prompting for reminders

- gcalcli/gcal.py
- gcalcli/ics.py
> Fix crash when importing empty ICS, add summary message w/ event count

- gcalcli/gcal.py
- gcalcli/ics.py
Quality-of-life improvement for scenarios like #730 so that it's easier to retry failed events with different settings (`--use-legacy-import` etc).
> Change import to dump ics file for any failed events

- gcalcli/cli.py
- gcalcli/utils.py
> util inspect-auth: fix unauthenticated case to print the right message

- gcalcli/gcal.py
> Stop using brightblack color by default (UX problems on dark bg)

- ChangeLog
- gcalcli/config.py
- pyproject.toml
> Switch from "toml" dep to "tomli" to fix failures reading config

- ChangeLog
- gcalcli/cli.py
> Fix `config edit` when missing dir blowing up with FileNotFoundError

- gcalcli/gcal.py
> Fix arg mismatch for gcalcli edit (allday arg)
